# docker service create --name registry --publish 127.0.0.1:5000:5000 registry:2
version: "2.2"
services:
  nginx:
    build: ./nginx
    image: ahu/nginx:v1
    restart: unless-stopped
    volumes:
      - ./store/letsencrypt:/etc/letsencrypt
      - ./store/log:/mnt/store/log
    ports:
      - "80:80"
      - "443:443"

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ahungry
    volumes:
      - ./mysql:/etc/mysql
    ports:
      - "3306:3306"

  mariadb-data:
    build: ./mariadb-data
    image: ahu/mariadb-data:v1
    volumes:
      - ./store/mariadb-data:/mnt/store/mariadb-data
    depends_on:
      - mariadb

  com.ahungry:
    build: ./deps/com.ahungry
    image: ahu/com.ahungry:v1
    restart: unless-stopped
    volumes: []
    environment:
      MYSQL_AHUNGRY_HOST: mariadb
      MYSQL_AHUNGRY_USERNAME: root
      MYSQL_AHUNGRY_PASSWORD: ahungry
    ports:
      - "5000:5000"
    depends_on:
      - mariadb-data

  com.ahungry.comments:
    user: "1000"
    build: ./deps/com.ahungry.comments
    image: ahu/com.ahungry.comments:v1
    restart: unless-stopped
    mem_limit: 256m
    mem_reservation: 128m
    volumes:
      - ./user-store/com.ahungry.comments:/home/dummy/.local
    ports:
      - "3001:3001"
